const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const en = path.join(root, 'en');
fs.mkdirSync(en, { recursive: true });

const pages = [
  'index.html',
  'associations-membres.html',
  'bureau-executif.html',
  'conseil-administration.html',
  'depliant.html',
  'depliant-print.html',
  'evenement.html',
  'jeux-interactifs.html',
  'mentions-legales.html',
  'mot-presidente.html',
  'politique-confidentialite.html',
  'repertoire-ecoles.html',
  'repertoire-medecins.html',
  'repertoire-paramedicaux.html',
  'temoignages-evenement.html'
];

const prefixes = ['styles/', 'js/', 'images/', 'feeds/', 'favicon', 'Partenaires/'];
let n = 0;

for (const page of pages) {
  const src = path.join(root, page);
  if (!fs.existsSync(src)) {
    console.log('skip', page);
    continue;
  }
  let html = fs.readFileSync(src, 'utf8');
  html = html.replace(/lang="fr"/, 'lang="en"');
  for (const p of prefixes) {
    const escaped = p.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const re = new RegExp('(href|src)="' + escaped, 'g');
    html = html.replace(re, '$1="../' + p);
  }
  html = html.replace(/href="en\//g, 'href="');
  fs.writeFileSync(path.join(en, page), html);
  n += 1;
  console.log('ok', page);
}

fs.writeFileSync(
  path.join(en, 'README.md'),
  '# English mirror (en/)\n\nGenerated by scripts/prepare-en.js from FR root HTML.\nTranslate copy; assets use `../`; wire lang-switcher with base `../`.\n'
);
console.log('done', n);
