# Prepare en/ mirror directory for English pages.
# Copies public HTML from site root, rewrites root-relative asset paths to ../,
# sets lang="en", and leaves a README placeholder note.
#
# Usage (from Sites root):
#   powershell -ExecutionPolicy Bypass -File scripts\prepare-en.ps1

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot
if (-not (Test-Path (Join-Path $Root 'index.html'))) {
  $Root = (Get-Location).Path
}

$EnDir = Join-Path $Root 'en'
New-Item -ItemType Directory -Force -Path $EnDir | Out-Null

$Pages = @(
  'index.html',
  'associations-membres.html',
  'bureau-executif.html',
  'conseil-administration.html',
  'depliant.html',
  'depliant-print.html',
  'evenement.html',
  'jeux-interactifs.html',
  'mentions-legales.html',
  'mot-presidente.html',
  'politique-confidentialite.html',
  'repertoire-ecoles.html',
  'repertoire-medecins.html',
  'repertoire-paramedicaux.html',
  'temoignages-evenement.html'
)

function Rewrite-EnHtml([string]$html) {
  $html = $html -replace 'lang="fr"', 'lang="en"'
  # Asset / script / stylesheet roots
  $prefixes = @('styles/', 'js/', 'images/', 'feeds/', 'favicon', 'Partenaires/')
  foreach ($p in $prefixes) {
    $html = $html -replace ('(href|src)="(' + [regex]::Escape($p) + ')', '$1="../$2'
  }
  # Sibling page links that stay in EN: leave bare .html; FR siblings become ../
  # Point language switcher EN self / FR parent (basic)
  $html = $html -replace 'href="en/', 'href="'
  return $html
}

$copied = @()
foreach ($page in $Pages) {
  $src = Join-Path $Root $page
  if (-not (Test-Path $src)) {
    Write-Warning "Skip missing: $page"
    continue
  }
  $raw = Get-Content -Path $src -Raw -Encoding UTF8
  $out = Rewrite-EnHtml $raw
  $dest = Join-Path $EnDir $page
  Set-Content -Path $dest -Value $out -Encoding UTF8
  $copied += $page
}

$readme = @"
# English mirror (en/)

Generated by scripts/prepare-en.ps1 from FR root HTML.

Next steps:
- Translate visible copy
- Fix internal nav links (use same filename in en/, ``../`` for assets)
- Wire lang-switcher: styles/lang-switcher.css + js/i18n-switcher.js with base ``../``

Pages copied: $($copied -join ', ')
"@
Set-Content -Path (Join-Path $EnDir 'README.md') -Value $readme -Encoding UTF8

Write-Host "Prepared en/ with $($copied.Count) pages:"
$copied | ForEach-Object { Write-Host "  - $_" }
